### ISSUE TITLE
Create a v2 protocol that does not use x509

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#1740]
Today the protocol is all x509 all the time, identity is extracted from certs and everyone needs a cert.

We recently did work to introduce JWTs and ed25519 keys for authentication part, today for those to be able to make requests a AAA service which will sign using a x509 key is required

So the goal is essentially to allow jwt+ed25519 to make requests without a AAA service.  This will be a v2 protocol, the server/client needs to be able to support both v1 and v2 protocols at the same time so that where needed a cert can be used for auth+sign to facilitate gradual move to new behaviors as inevitably this will require changes to provisioner, replicator and many other components.

We should look at the mechanics for issuing JWTs a bit more now too as this will essentially end up replacing the role of the CA entirely.  Brokers of course will still need x509 certs to support TLS - but given that we do chain of trust verification on the connection with signatures and keys it might be that TLS using tempoary certs would be entirely possible and safe.

v2 protocol need to also get rid of the whole cached cert thing as JWTs are short lived.  This will therefor probably require a full revisit of security providers.  If possible v1 protocol/security should also remove the cert cache as its just annoying.

The goals and design can be found in the [ADR](https://choria-io.github.io/go-choria/adr/001/index.html).

Changes:

 - [x] for v2 move from `choria:request:2` to `io.choria.protocol.v2.request` etc which is more in line with recent schemas etc
 - [x] Remove the concept of a cert cache entirely from v1 to simplify v2 effort https://github.com/choria-io/go-choria/pull/1842
 - [x] also remove cache from the puppet modules (was not needed as modules are all puppet sec that does it on its own)
 - [x] tokens should all be signable using ed25519 https://github.com/choria-io/go-choria/pull/1743
 - [x] create a permission to grant/deny access to choria fleet in client jwts
 - [x] add design doc https://github.com/choria-io/go-choria/blob/main/protocol/v2/ADR.md
 - [x] move to a `[]byte` orientated api where possible https://github.com/choria-io/go-choria/pull/1844
 - [x] remove string orientated security interface items https://github.com/choria-io/go-choria/commit/ec2cf7e1bd46ff5258724777afe1bca65807d8c3
 - [x] create a network packet analyzer, ongoing refinements
 - [x] when v2 protocol and security is use the default collective should be `choria` https://github.com/choria-io/go-choria/pull/1885
 - [x] Extract schema validation from v1 for reuse between protocols https://github.com/choria-io/go-choria/pull/1852
 - [x] Upgrade to a schema validator that handles new standards https://github.com/choria-io/go-choria/pull/1853
 - [x] Create ad publish schemas for v2 protocol, use for message validation
 - [x] Turn the protocol strings into a defined type with custom marshaling etc https://github.com/choria-io/go-choria/pull/1864
 - [x] Auto select Message protocol based on selected security technology https://github.com/choria-io/go-choria/pull/1865
 - [x] update `choria-io/schemas` with final protocol schemas https://github.com/choria-io/schemas/pull/77
 - [x] use the new security provider to allow submit to send authenticated messages https://github.com/choria-io/go-choria/issues/1873
 - [x] server registration messages should optionally be signed https://github.com/choria-io/go-choria/pull/1885
 - [x] Support seed strings in `plugin.choria.network.client_signer_cert` and `server_signer_cert`, support multiples of each https://github.com/choria-io/go-choria/pull/1885
 - [x] ~Consider signing lifecycle events and auto agent events~ - won't do, minimal value
 - [x] Client tokens need additional pub and sub properties https://github.com/choria-io/go-choria/pull/1887
 - [x] Expose the public data (cert/token) from secure request to request. This is to give agents access to OPA etc https://github.com/choria-io/go-choria/pull/1897
 - [x] AAA Sign requests should be signed by the seed and AAA Service should verify it https://github.com/choria-io/aaasvc/issues/114 and https://github.com/choria-io/go-choria/issues/1898
 - [x] Issuers should be in a chain of trust https://github.com/choria-io/go-choria/issues/1900
 - [x] Support signing keys in vault for the JWT CLI and tokens API see https://thecodeslinger.org/2021/03/28/sign-and-verify-jwt-with-hashicorp-vault/ https://github.com/choria-io/go-choria/pull/1910
 - [x] Ensure auth errors are not terminal with `nats.IgnoreAuthErrorAbort()` https://github.com/choria-io/go-choria/pull/1912
 - [x] For provisioning we need a JWT permission that a client is allowed to provisioning nodes and that should be checked instead of all the TLS requirements in `handleProvisioningUserConnection()` https://github.com/choria-io/go-choria/issues/1913
 - [x] Support protocol v2 provisioning mode server connections https://github.com/choria-io/go-choria/issues/1916
 - [x] Client token opa policies should be evaluated on servers for a server-side configured policy free deployment. 
https://github.com/choria-io/go-choria/issues/1924 https://github.com/choria-io/aaasvc/issues/126
 - [x] Ensure adapters work in with org issuer mode https://github.com/choria-io/go-choria/pull/1936
 - [x] Use ksuid for request IDs in proto v2 https://github.com/choria-io/go-choria/pull/1947
 - [x] In issuer mode, when a fully verified tls connection comes in, give them access to all subjects except choria ones. They can use core nats and streams only and this should probably be an opt-in here https://github.com/choria-io/go-choria/pull/1951
 - [x] Extract the `tokens` dependency into its own small package with just jwt dependency.  Also add to it the nats helper for `UserJWT`.  Stream replicator, actyncjobs and more would use that and I dont want to depend on full choria. https://github.com/choria-io/tokens
 - [x] Verify state check functions correctly, choria compose shows a issue there `cert_expire_seconds=-9223372036` this should be 0 there and should instead report token expiry https://github.com/choria-io/go-choria/issues/1959
 - [x] Ensure chain issuers can be issued using the cli from a vault hosted org issuer https://github.com/choria-io/go-choria/pull/1963
 - [x] JWT monitor https://github.com/choria-io/go-choria/issues/1972
 - [x] Support allowing governor access in JWT CLI https://github.com/choria-io/go-choria/issues/1978
 - [x] Allow a v1 protocol provisioner using cert+0username+password to connect the provisioning account when enabled via a opt-in setting. This to facilitate migrating a brownfield environment so that too old servers can be special cased https://github.com/choria-io/go-choria/pull/1993
 - [x] Create integration tests to show chained tokens working end to end
 - [x] Ensure basic client JWTs with no additional properties set are default deny https://github.com/choria-io/go-choria/pull/2000
 - [x] Verify that the `NetworkDenyServers` and `NetworkAllowedClientHosts` options still work with jwt connections
 - [ ] Consider removing trusted signers after https://github.com/choria-io/go-choria/issues/1900
 - [ ] Refactor security into instances so they can share correct loggers and have contexts from the right parent
 - [ ] Client connections should disconnect on jwt expire deadline - NATS server feature pending
 - [ ] revisit existing settings used to find the token and seed and see if there are less confusing ways

## Related

 - [x] AAA Service to sign v2 requests https://github.com/choria-io/aaasvc/pull/113 
 - [x] AAA Service login and signers should support signing chains https://github.com/choria-io/aaasvc/pull/117
 - [x] Provisioner should support signing chains https://github.com/choria-io/provisioner/issues/177
 - [x] Replicator should support connecting to choria with choria creds https://github.com/choria-io/stream-replicator/issues/67
