### ISSUE TITLE
Add an election wrapper

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#1755]
We want to be able to run a command under election control.

 * A cron where you should only run if you win, if you timeout exit
 * A case where a long running process writes `/tmp/active.txt` frequently on which ever macine is leader

We'll use the existing LE bucket, so just:

## Run a command under election

Basic idea is, if I am the leader I run `doit.sh`, if not I signal if 15 then 9.

```
$ choria election run MYCOMMAND /tmp/doit.sh
```

This can have a timeout that if not leader within a period just give up:

```
$ choria election run MYCOMMAND /tmp/doit.sh --max-wait 1m
```

And perhaps rather than stop/start the process we signal it:

```
$ choria election run MYCOMMAND /tmp/doit.sh --won USR1 --lost USR2
```

## Mark a machine as active

Often teams have like a pair of cron servers and rather than have every cron do its own LE you can just mark a machine as active:

```
$ choria election file CRON /tmp/active.txt
```

This will on campaign interval write to the file so it exists+is new, otherwise just rm the file.

## Utilities

```
$ choria election info <bucket>
```

Show config, history keys etc. optional bucket name defaults to choria default election bucket

```
$ choria election evict <election>
```

Removes the current leader

# TODO

 - [x] `choria election file` https://github.com/choria-io/go-choria/pull/1758
 - [x] `choria election run` https://github.com/choria-io/go-choria/pull/1759
 - [x] `choria election info` https://github.com/choria-io/go-choria/pull/1762
 - [x] `choria election evict` to remove current leader https://github.com/choria-io/go-choria/pull/1764
 - [x] docs https://github.com/choria-io/website/commit/57b757f782d19f37c86b76f95682a1c0cd3b3bf8

**Comment by vjanelle** [comment]
Something more like `choria election run --win USR1 --lose USR2 --timeout 10 -- MYCOMMAND --args-to-my-command`

**Comment by ripienaar** [comment]
I can now do that yes, i think earlier versions of cli parser couldnt

**Comment by vjanelle** [comment]
then for the docs we could do a simple shell script with trap handlers as a demo.
