### ISSUE TITLE
support hosting autonomous agents

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#563]
## Use Cases

Autonomous agents would allow us to offer continuous management of a node or small group of nodes without active interaction like via RPC.

You want to build a HVAC system - monitor air quality, turn on when needed, turn off when above threshold.  Interaction with the HVAC, sensors etc should be via external tools.

You wish to continuously manage a docker container - install it at a prescribed version, health check it, monitor its the up and still the desired version.  Desired version is stored in a JSON file, when the file updates redeploy the container to the new desired version and go back to the monitor/remediate cycle.

Run something as if its a cron on a regular interval but if a specifically watched file update on the system immediately run instead of waiting for the cron.

A small cluster of nodes can be health checked by a controller node, when one of them are in problem ansible playbooks can be run to remediate the situation - or scale the cluster on demand.

## Design overview

Each autonomous agent should be described as a FSM.  The states and transitions are arbitrary and defined in the machine specification - YAML for now later perhaps HCL

Watchers are defined that run when the machine enter a given state or regularly while it is in a given state.  Watchers can execute commands and or watch files for change.  Periodically poll a web service or watch a consul key.

We'll start with just exec and file.

State changes, watch actions and periodic watch statusses are published as standard choria events.  Dashboards can be built by passive listening on a network like the tally tool does.

Machines can be downloaded from HTTP sources in the form of a archive.  Download is on demand by RPC calls into choria_util.

## Interface

Each choria server should be able to host a number of these agents and emit the events from them.  A cli tool should also be able to run an agent locally and events etc are logged to the console.  It should be possible to see a DOT graph of the agent states.

## TODO

 - [x] basic runnable machine
 - [x] manifest schema
 - [x] cli running
 - [x] dot graph generator
 - [x] additional environment vars for exec like a config level proxy setting 
 - [x] timeouts on the commands with a default of 10 seconds
 - [ ] hashes for files
 - [ ] inotify for files
 - [ ] controls for concurrent execution of watchers - machine level exclusive, node level exclusive with timeout
 - [x] basic choria server host
 - [x] event schemas
 - [x] event emitter
 - [x] choria_util for forcing event changes
 - [x] choria_util to view current machines and states
 - [x] watch a directory for machines, start and stop as directory change
 - [x] JSON schema validate and a `machine validate` command
 - [x] splay the startup of a machine to spread load
 - [x] support suppressing every-run state announces for some execs
 - [x] view events on the cli

**Comment by ripienaar** [comment]
closing this in favur of individual tickets going forward
