### ISSUE TITLE
Support NATS 2.0 multi tenancy

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#612]
## Overview

NATS 2.0 supports multi tenancy using a tiered operator/account/user setup, nodes/clients are users while a tenant like a particular business group is an account and the operator is who runs the server.

Accounts are isolated name spaces on the NATS 2.0 server meaning that users belonging to account HR cannot see any thing in account OPS.  This is like sub collectives but much stronger isolation. It's possible to allow cross account comms but probably less useful for us - though perhaps for adapters that would be useful.

We have to support this multi tenancy model:

 - [ ] On a basic level nothing should change for existing setups, no additional configuration burdon
 - [x] old agents and clients should be supported via leaf nodes to tie them to an account
 - [ ] Provisioning should support enrolling new machines as users with strict allow/deny rules in the generated JWT
 - [x] Nodes and clients should support using the new credentials (https://github.com/choria-io/go-choria/pull/620)
 - [ ] Broker should be based on the new setup and support this style auth in clusters
 - [x] Will require new go and go mod.  EOL for rhel5.

## Provisioning

 - [ ] The server should support an additional configuration that identifies which account it belongs to, this should be a path to a JWT file the operator provide and sign etc, should not expire but should be issued by the operator of the orchestration service
 - [ ] During provisioning this jwt should be exposed by `rpcutil#inventory`
 - [ ] the `choria_provision#gencsr` should be extended to also support generating the nkeys needed etc
 - [ ] The provisioner should be extended to generate not just the config but also the JWT that should go on the node.  This should include allow/deny lines for what it can communicate with, use https://github.com/nats-io/jwt to create the compatible tokens

## Clients

- [x] New versions of NATS related libraries
- [ ] Clients should support requesting a new JWT for accessing the service from the AAA Service, they would also send along a signed JWT for the account they wish to access
- [ ] AAA Service should issue nats JWTs with appropriate allow/deny lists
- [ ] Inevitably both ruby and go
- [x] should support connecting to NGS
- [x] should support using credentials

## Brokers

 - [x] Basic NATS 2.0 upgrade requiring no user visible changes
  - [x]  Additional config options (with sane defaults) for the paths to key stores etc around the new auth features
 - [x] Support leaf nodes to enable auth domain traversal - so that unauthenticated provisioning modes can hit a leaf node and assume an appropriate account for provisioning (https://github.com/choria-io/go-network-broker/issues/38)
 - [x] Support gateways so that remote sites can have local brokers thats reachable from a central place where services such a provisioning and more runs (https://github.com/choria-io/go-network-broker/issues/42)
 - [x] Will need a new `AccountResolver` set using `Server.SetAccountResolver` to obtain JWT tokens from a local file store rather than the supported dependency on `nats-account-server` which is v.hard to make reliable without k8s type systems. We might also look to support something like consul (file store https://github.com/choria-io/go-network-broker/issues/29 pausing change monitor need) 
 - [x] Support setting a system account (https://github.com/choria-io/go-network-broker/pull/34)
 - [ ] Utility to view system events and notify of account jwt changes if a system account is known
 - [x] Federation and Adapters should accept creds, can be the same one for now set via the same config option (https://github.com/choria-io/go-choria/pull/620 should have solved this)
 - [x] per leaf/gateway remote TLS settings to facilitate cross CA connections etc (https://github.com/choria-io/go-network-broker/issues/48)
 - [ ] Updated Prometheus stats for leaf and gateway connections and traffic
